# Generated by Django 4.1.7 on 2023-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='expired',
            field=models.DateTimeField(blank=True),
        ),
    ]
