# Generated by Django 4.1.7 on 2023-03-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_code_alter_account_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='expired',
            field=models.DateTimeField(),
        ),
    ]
