# Generated by Django 4.1.7 on 2023-03-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_email_otp_emailotp_rename_sms_otp_smsotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailotp',
            options={'ordering': ('-expired',)},
        ),
        migrations.AlterModelOptions(
            name='smsotp',
            options={'ordering': ('-expired',)},
        ),
    ]
