# Generated by Django 4.1.7 on 2023-03-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailotp_options_alter_smsotp_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailotp',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='smsotp',
            old_name='User',
            new_name='user',
        ),
    ]
