# Generated by Django 4.1.7 on 2023-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsotp',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='آدرس ایمیل'),
        ),
    ]
