# Generated by Django 4.1.7 on 2023-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_smsotp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsotp',
            name='email',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='آدرس ایمیل'),
        ),
    ]
